var error_msg = {
    firstname:  "請輸入名字",
	lastname:   "請輸入姓氏",
	hkjcmembershipno:   "請輸入馬會會員編號",
    tel: "請輸入有效的電話號碼",
	email: "請輸入有效的電郵地址",
	fax: "請輸入有效的傳真號碼",
	checkbox: "請選擇一項",
	selectparticipant: "請選擇參加人數",
	syndicate_name:"請輸入賽馬團體名稱",
	ba_account:"請輸入BA帳戶編號",
	noempty: "請輸入",
	agentname: "請輸入代理人姓名",
	agentaddress: "請輸入代理人地址",
	agenttel: "請輸入有效的代理人電話號碼",
	agentbusinessno: "請輸入有效的代理人電郵",
	agentfax: "請輸入有效的代理人傳真號碼",
	totalsum: "請輸入港元總額",
    captcha: "請輸入有效的驗證碼",
    captcha_wrong: "請輸入有效的驗證碼",
    privacy: "Privacy",
    confirm: "請確認",
    submission: "提交錯誤! 請稍後再試"
};

var dberror_msg = {
	firstname: "請輸入名字",
	lastname: "請輸入姓氏",
	fax: "請輸入有效的傳真號碼",
	tel: "請輸入有效的電話號碼",
	email: "請輸入有效的電郵地址",
	hkjcmembershipno: "請輸入馬會會員編號",
	agentdetail: "",
	permittype: "請選擇馬匹進口許可證類別",
	ownertype: "請選擇馬主類別",
	syndicatename: "請輸入賽馬團體名稱",
	baaccount:"請輸入BA帳戶編號",
	breezeupradio: "請選擇馬匹試跑示範選項",
	breezeupparticipant: "請輸入馬匹試跑示範參加人數",
	breezeupusbradio: "請選擇馬匹試跑示範USB手指選項",
	purchaseradio: "請選擇拍賣會選項",
	saleparticipant: "請選擇參加人數",
	totalsumradio: "請選擇購馬支出選項",
	totalsum: "請輸入港元總額",
	agentname: "請輸入代理人姓名",
	agentaddress: "請輸入代理人地址",
	agenttel: "請輸入有效的代理人電話號碼",
	agentbusinessno: "請輸入有效的代理人電郵",
	agentfax: "請輸入有效的代理人傳真號碼"
}