var error_msg = {
    firstname:  "Please enter First Name",
	lastname:   "Please enter Last Name",
	hkjcmembershipno:   "Please enter HKJC Membership No.",
    tel: "Please enter a valid Tel number",
	email: "Please enter a valid Email address",
	fax: "Please enter a valid Fax number",
	checkbox: "Please select an option",
	selectparticipant: "Please select Total number of participant(s)",
	syndicate_name:"Please enter Syndicate Name",
	ba_account:"Please enter BA Account No.",
	noempty: "Please fill in",
	agentname: "Please enter Name of Agent",
	agentaddress: "Please enter Address of Agent",
	agenttel: "Please enter a valid Agent's Tel No.",
	agentbusinessno: "Please enter a valid Agent's Email",
	agentfax: "Please enter a valid Agent's Fax No.",
	totalsum: "Please enter Total sum of HK$",
    captcha: "Please enter the correct verification code",
    captcha_wrong: "Please enter the correct verification code",
    privacy: "Privacy",
    confirm: "Please confirm",
    submission: "Submission Error! Please try again later."
};

var dberror_msg = {
	firstname: "Please enter First Name",
	lastname: "Please enter Last Name",
	fax: "Please enter a valid Fax number",
	tel: "Please enter a valid Tel number",
	email: "Please enter a valid Email address",
	hkjcmembershipno: "Please enter HKJC Membership No.",
	agentdetail: "",
	permittype: "Please select Permit Type",
	ownertype: "Please select Owner Type",
	syndicatename: "Please enter Syndicate Name",
	baaccount:"Please enter BA Account No.",
	breezeupradio: "Please select the Breeze-Up option",
	breezeupparticipant: "Please enter Breeze-Up Total number of participant(s)",
	breezeupusbradio: "Please select theBreeze-Up USB Flash Drive option",
	purchaseradio: "Please select the Sale option",
	saleparticipant: "Please enter Sale Total number of participant(s)",
	totalsumradio: "Please select the limitation option",
	totalsum: "Please enter Total sum of HK$",
	agentname: "Please enter Name of Agent",
	agentaddress: "Please enter Address of Agent",
	agenttel: "Please enter a valid Agent's Tel No.",
	agentbusinessno: "Please enter a valid Agent's Email",
	agentfax: "Please enter a valid Agent's Fax No."
}
